### ISSUE TITLE
Android 11 testing

### ISSUE THREAD

**Issue by grote** [seedvault-app/seedvault#152]
A lot has changed for the Android 11 release. Here's a suggestion for what to test apart from the usual test plan.

### Before Backup

* [ ] Install a few apps that [use **app bundles**](https://developer.android.com/platform/technology/app-bundle#size-savings-because-of-android-app-bundles)
* [ ] Create/Import a few **contacts** and store them on-device only (not on sync account)
* [ ] [Create](https://github.com/stevesoltys/seedvault/issues/93#issuecomment-685865991) some **call log** entries 
* [ ] Check that **Nextcloud** is [always](https://github.com/stevesoltys/seedvault/commit/e3406613a63b7fe5b3e8150a7ff75fe7b418dbdd) offered as a storage option, even when not installed
* [ ] Check whether **available storage** [is shown](https://github.com/stevesoltys/seedvault/commit/25695d72b8a7d8cd33800f2025829485620bfd6c)
* [ ] Exclude some apps from backup and see if your **exclusion setting** [doesn't change back](https://github.com/stevesoltys/seedvault/issues/83)

### After backup

* [ ] Check that UI doesn't [hang](https://github.com/stevesoltys/seedvault/commit/fbdfa40300e009a79e81658aa0aa7746fe303d8f) when opening **app status screen** and shows progress bar instead (briefly)
* [ ] Check app status screen for correct **status messages** and time stamps
* [ ] Check UI in [**other languages**](https://github.com/stevesoltys/seedvault/commit/741e5ef1a0a4c5ab776930849564821090ba4af3)
* [ ] Manually delete some `.apk` files (randomly from base and splits) to **provoke errors** during restore

### During restore

* [ ] Try to **install** some apps manually that failed to install
* [ ] See if **app store opens** that you had installed the app with before (known [not to work for F-Droid if not using the privext](https://gitlab.com/fdroid/fdroidclient/-/issues/2085))

### After restore

* [ ] Check if the **status messages of the apps** are as expected (e.g. backup not allowed)
* [ ] Try to install some apps manually that you didn't to install before data restore, to see if **auto-restore** works
* [ ] check if all **contacts got restored** as expected
* [ ] check if all **call logs got restored** as expected

Generally, it will be nice to test against flash drive and [Nextcloud 3.14](https://github.com/nextcloud/android/issues/6746). The latter can still fail on network issues.

If one has more time, one can test the behavior when **not fulfilling the conditions for K/V backup** for more than a day:
* not charging the phone
* not turning on internet
* not making storage available
    * not connecting it to the internet when Nextcloud is used
    * not plugging in flash drive when it is used as storage

Afterwards, even manually triggered backups should be incremental, e.g. not backing up all `@pm@` data and all call logs again.

**Comment by chirayudesai** [comment]
Nextcloud 3.14 tracking: https://github.com/nextcloud/android/issues/6746

**Comment by Uldiniad** [comment]
hit this on my second test run
```
12-17 16:26:59.616 11526 11749 E AndroidRuntime: FATAL EXCEPTION: Binder:11526_4
12-17 16:26:59.616 11526 11749 E AndroidRuntime: Process: com.stevesoltys.seedvault, PID: 11526
12-17 16:26:59.616 11526 11749 E AndroidRuntime: java.lang.AssertionError
12-17 16:26:59.616 11526 11749 E AndroidRuntime:        at com.stevesoltys.seedvault.transport.backup.KVBackup.performBackup(KVBackup.kt:70)
12-17 16:26:59.616 11526 11749 E AndroidRuntime:        at com.stevesoltys.seedvault.transport.backup.BackupCoordinator.performIncrementalBackup(BackupCoordinator.kt:259)
12-17 16:26:59.616 11526 11749 E AndroidRuntime:        at com.stevesoltys.seedvault.transport.ConfigurableBackupTransport$performBackup$1.invokeSuspend(ConfigurableBackupTransport.kt:148)
12-17 16:26:59.616 11526 11749 E AndroidRuntime:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-17 16:26:59.616 11526 11749 E AndroidRuntime:        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
12-17 16:26:59.616 11526 11749 E AndroidRuntime:        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:270)
12-17 16:26:59.616 11526 11749 E AndroidRuntime:        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
12-17 16:26:59.616 11526 11749 E AndroidRuntime:        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
12-17 16:26:59.616 11526 11749 E AndroidRuntime:        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
12-17 16:26:59.616 11526 11749 E AndroidRuntime:        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
12-17 16:26:59.616 11526 11749 E AndroidRuntime:        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
12-17 16:26:59.616 11526 11749 E AndroidRuntime:        at com.stevesoltys.seedvault.transport.ConfigurableBackupTransport.performBackup(ConfigurableBackupTransport.kt:147)
12-17 16:26:59.616 11526 11749 E AndroidRuntime:        at android.app.backup.BackupTransport$TransportImpl.performBackup(BackupTransport.java:704)
12-17 16:26:59.616 11526 11749 E AndroidRuntime:        at com.android.internal.backup.IBackupTransport$Stub.onTransact(IBackupTransport.java:626)
12-17 16:26:59.616 11526 11749 E AndroidRuntime:        at android.os.Binder.execTransactInternal(Binder.java:1159)
12-17 16:26:59.616 11526 11749 E AndroidRuntime:        at android.os.Binder.execTransact(Binder.java:1123)
12-17 16:26:59.674  1606 11856 E KeyValueBackupTask: Transport error backing up @pm@
12-17 16:26:59.674  1606 11856 E KeyValueBackupTask: android.os.DeadObjectException
12-17 16:26:59.674  1606 11856 E KeyValueBackupTask:    at android.os.BinderProxy.transactNative(Native Method)
12-17 16:26:59.674  1606 11856 E KeyValueBackupTask:    at android.os.BinderProxy.transact(BinderProxy.java:550)
12-17 16:26:59.674  1606 11856 E KeyValueBackupTask:    at com.android.internal.backup.IBackupTransport$Stub$Proxy.performBackup(IBackupTransport.java:1157)
12-17 16:26:59.674  1606 11856 E KeyValueBackupTask:    at com.android.server.backup.keyvalue.KeyValueBackupTask.transportPerformBackup(KeyValueBackupTask.java:1078)
12-17 16:26:59.674  1606 11856 E KeyValueBackupTask:    at com.android.server.backup.keyvalue.KeyValueBackupTask.sendDataToTransport(KeyValueBackupTask.java:1053)
12-17 16:26:59.674  1606 11856 E KeyValueBackupTask:    at com.android.server.backup.keyvalue.KeyValueBackupTask.sendDataToTransport(KeyValueBackupTask.java:567)
12-17 16:26:59.674  1606 11856 E KeyValueBackupTask:    at com.android.server.backup.keyvalue.KeyValueBackupTask.backupPm(KeyValueBackupTask.java:669)
12-17 16:26:59.674  1606 11856 E KeyValueBackupTask:    at com.android.server.backup.keyvalue.KeyValueBackupTask.run(KeyValueBackupTask.java:358)
12-17 16:26:59.674  1606 11856 E KeyValueBackupTask:    at java.lang.Thread.run(Thread.java:923)
12-17 16:26:59.674  1606  1606 E TransportClient: ConfigurableBackupTransportService#15: Service disconnected: client UNUSABLE
12-17 16:26:59.674  1606 11856 E KeyValueBackupTask: Error during PM metadata backup
12-17 16:26:59.674  1606 11856 E KeyValueBackupTask: com.android.server.backup.keyvalue.TaskException: android.os.DeadObjectException
12-17 16:26:59.674  1606 11856 E KeyValueBackupTask:    at com.android.server.backup.keyvalue.KeyValueBackupTask.transportPerformBackup(KeyValueBackupTask.java:1086)
12-17 16:26:59.674  1606 11856 E KeyValueBackupTask:    at com.android.server.backup.keyvalue.KeyValueBackupTask.sendDataToTransport(KeyValueBackupTask.java:1053)
12-17 16:26:59.674  1606 11856 E KeyValueBackupTask:    at com.android.server.backup.keyvalue.KeyValueBackupTask.sendDataToTransport(KeyValueBackupTask.java:567)
12-17 16:26:59.674  1606 11856 E KeyValueBackupTask:    at com.android.server.backup.keyvalue.KeyValueBackupTask.backupPm(KeyValueBackupTask.java:669)
12-17 16:26:59.674  1606 11856 E KeyValueBackupTask:    at com.android.server.backup.keyvalue.KeyValueBackupTask.run(KeyValueBackupTask.java:358)
12-17 16:26:59.674  1606 11856 E KeyValueBackupTask:    at java.lang.Thread.run(Thread.java:923)
12-17 16:26:59.674  1606 11856 E KeyValueBackupTask: Caused by: android.os.DeadObjectException
12-17 16:26:59.674  1606 11856 E KeyValueBackupTask:    at android.os.BinderProxy.transactNative(Native Method)
12-17 16:26:59.674  1606 11856 E KeyValueBackupTask:    at android.os.BinderProxy.transact(BinderProxy.java:550)
12-17 16:26:59.674  1606 11856 E KeyValueBackupTask:    at com.android.internal.backup.IBackupTransport$Stub$Proxy.performBackup(IBackupTransport.java:1157)
12-17 16:26:59.674  1606 11856 E KeyValueBackupTask:    at com.android.server.backup.keyvalue.KeyValueBackupTask.transportPerformBackup(KeyValueBackupTask.java:1078)
12-17 16:26:59.674  1606 11856 E KeyValueBackupTask:    ... 5 more
```

**Comment by grote** [comment]
Did you do anything out of the ordinary to produce the first error? Were there any errors in the log before? It looks like the K/V backup was left in an unexpected state like when not teared down properly before.

**Comment by Uldiniad** [comment]
I didn't do anything that I'd consider out of the ordinary to produce this. I tried reproducing with the same steps I did and it didn't happen again. There were no errors relating to backup before in the log. I'm not sure how it would have gotten in the state given that it failed on the first attempt (no prior attempts in that run)

**Comment by Uldiniad** [comment]
Comment in-progress (will also include screenshots):

### Before Backup

* [ ] Install a few apps that [use **app bundles**](https://developer.android.com/platform/technology/app-bundle#size-savings-because-of-android-app-bundles)
* [ ] Create/Import a few **contacts** and store them on-device only (not on sync account)
* [ ] [Create](https://github.com/stevesoltys/seedvault/issues/93#issuecomment-685865991) some **call log** entries 
* [ ] Check that **Nextcloud** is [always](https://github.com/stevesoltys/seedvault/commit/e3406613a63b7fe5b3e8150a7ff75fe7b418dbdd) offered as a storage option, even when not installed
* [ ] Check whether **available storage** [is shown](https://github.com/stevesoltys/seedvault/commit/25695d72b8a7d8cd33800f2025829485620bfd6c)
* [ ] Exclude some apps from backup and see if your **exclusion setting** [doesn't change back](https://github.com/stevesoltys/seedvault/issues/83)

### After backup

* [ ] Check that UI doesn't [hang](https://github.com/stevesoltys/seedvault/commit/fbdfa40300e009a79e81658aa0aa7746fe303d8f) when opening **app status screen** and shows progress bar instead (briefly)
* [ ] Check app status screen for correct **status messages** and time stamps
* [ ] Check UI in [**other languages**](https://github.com/stevesoltys/seedvault/commit/741e5ef1a0a4c5ab776930849564821090ba4af3)
* [ ] Manually delete some `.apk` files (randomly from base and splits) to **provoke errors** during restore

### During restore

* [ ] Try to **install** some apps manually that failed to install
* [ ] See if **app store opens** that you had installed the app with before (known [not to work for F-Droid if not using the privext](https://gitlab.com/fdroid/fdroidclient/-/issues/2085))

### After restore

* [ ] Check if the **status messages of the apps** are as expected (e.g. backup not allowed)
* [ ] Try to install some apps manually that you didn't to install before data restore, to see if **auto-restore** works
* [ ] check if all **contacts got restored** as expected
* [ ] check if all **call logs got restored** as expected

**Comment by grote** [comment]
>  UNEXPECTED: Available storage was NOT shown

I saw the same on AOSP 11: for some reason the available storage isn't reported anymore.

**Comment by Uldiniad** [comment]
side note: I find the waiting to backup message a little confusing after a backup is performed. I have noticed it happens in contacts for example when there are no contacts

**Comment by grote** [comment]
Noteworthy observations:

* `com.android.providers.settings` is shown in the screenshot to be backed up, but its restore failed. The logcat shows it missing from the set of apps to be restored for some reason.
* `com.reddit.frontpage` completed backup and restore. We should check if it just failed silently or if their backup is broken, so that is why they show their setup wizard and don't save the theme?
* `com.android.calllogbackup`  is shown in the screenshot to be backed up, but its restore failed. The logcat shows it as part of the set of apps to be restored, but then the system never attempts to restore it. Maybe because of #182?

**Comment by bettyvschmartz** [comment]
> side note: I find the waiting to backup message a little confusing after a backup is performed. I have noticed it happens in contacts for example when there are no contacts

Should this be raised as a separate issue? I also notice on backup completion the message `...waiting to backup` on both _Local Contacts_ and _SMS Messages_. I assume this is because I have cloud-based contacts (no local, device contacts) and have another default SMS app (native SMS app therefore has no messages).

Would it not be better to change to something like `Nothing to backup`?

-- BVS

**Comment by chirayudesai** [comment]
> > side note: I find the waiting to backup message a little confusing after a backup is performed. I have noticed it happens in contacts for example when there are no contacts
> 
> Should this be raised as a separate issue? I also notice on backup completion the message `...waiting to backup` on both _Local Contacts_ and _SMS Messages_. I assume this is because I have cloud-based contacts (no local, device contacts) and have another default SMS app (native SMS app therefore has no messages).
> 
> Would it not be better to change to something like `Nothing to backup`?
> 
> -- BVS

Yes, separate issue would be useful, we should try to fix this, "Nothing to backup" would be better indeed.

Patches welcome as well!

**Comment by grote** [comment]
> "Nothing to backup" would be better indeed.

I don't agree here, because the message just means that the system didn't ask us to back up something. There's a separate message for no data already.

**Comment by chirayudesai** [comment]
> > "Nothing to backup" would be better indeed.
> 
> I don't agree here, because the message just means that the system didn't ask us to back up something. There's a separate message for no data already.

Yeah, so we can use that then, the point is that both would still be better than "Waiting to backup"
